# Generated by Django 4.2 on 2023-08-03 18:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=100,
                scale=None,
                size=[500, 467],
                upload_to="item_images",
            ),
        ),
    ]
